YT_COOKIES_FILE = r"C:\Users\Mefodii\Downloads\cookies.txt"

CONTENTING_TEMP_ROOT = r"E:\Tnetnoc\tnetnoc_watchers"
CONTENTING_VIDEO_ROOT = r"G:\Filme"
CONTENTING_AUDIO_ROOT = r"G:\Music\yt_watchers"
PLAYLIST_ROOT = r"G:\Music\Relax & Listen"
PLAYLIST_BUFFER_ROOT = r"H:\My Music\TBD"

# ###################################
# REGANAM TNETNOC PATHS
# ###################################
YOUTUBE_INPUT_FILE = "to_download.txt"
YOUTUBE_JSON_FILE = "yt_download.json"
YOUTUBE_WATCHERS_FILE = "yt_watchers.json"
YOUTUBE_WATCHERS_PGM_FILE = "yt_watchers_pgm.json"
NORMALIZATION_FILE = "normalization.txt"

YOUTUBE_DK_FILE = "dk.txt"

REGANAM_TNETNOC_ROOT = "E:\\Tnetnoc"
INPUT_FILES_PATH = REGANAM_TNETNOC_ROOT + "\\input"
LEGACY_WATCHERS_PATH = INPUT_FILES_PATH + "\\watchers"
LOGS_FILES_PATH = REGANAM_TNETNOC_ROOT + "\\logs"
WATCHER_JSON_DB_PATH = REGANAM_TNETNOC_ROOT + "\\_db"
WATCHERS_DOWNLOAD_PATH = REGANAM_TNETNOC_ROOT + "\\tnetnoc_watchers"
YOUTUBE_RESULT_PATH = REGANAM_TNETNOC_ROOT + "\\tnetnoc_downloads"
TESTS_PATH = REGANAM_TNETNOC_ROOT + "\\tests"

FILES_VIDEO_ARCHIVE_PATH = "G:\\Filme"
FILES_AUDIO_ARCHIVE_PATH = "G:\\Music\\yt_watchers"
PLAYLIST_FILES_PATH = "E:\\Google Drive\\Mu\\plist"

# FULL PATH
YOUTUBE_WATCHERS_PATH = '/'.join([INPUT_FILES_PATH, YOUTUBE_WATCHERS_FILE])
YOUTUBE_WATCHERS_PGM_PATH = '/'.join([INPUT_FILES_PATH, YOUTUBE_WATCHERS_PGM_FILE])
NORMALIZATION_PATH = '/'.join([INPUT_FILES_PATH, NORMALIZATION_FILE])

API_KEY_PATH = '/'.join([INPUT_FILES_PATH, YOUTUBE_DK_FILE])

# LOGS
YOUTUBE_API_LOG = LOGS_FILES_PATH + "/api_logs.txt"
