# Generated by Django 5.0.6 on 2024-07-25 05:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('alias', models.CharField(blank=True, max_length=500)),
                ('monitoring', models.BooleanField(default=False)),
                ('check_date', models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('releasing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Album', 'Album'), ('Collab', 'Collab'), ('Compilation', 'Compilation'), ('EP', 'EP'), ('Feat', 'Feat'), ('Misc', 'Misc'), ('Other', 'Other'), ('Single', 'Single')], default='Other', max_length=50)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('unknown_playlist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('None', 'None'), ('Like', 'Like'), ('Dislike', 'Dislike'), ('Missing', 'Missing'), ('Downloaded', 'Downloaded'), ('In Library', 'In Library')], default='None', max_length=50)),
                ('is_clean', models.BooleanField(default=False)),
                ('double_checked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.artist')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(related_name='releases', through='listening.ReleaseArtists', to='listening.artist'),
        ),
        migrations.CreateModel(
            name='ReleaseTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('needs_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='listening.release')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_tracks', to='listening.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', through='listening.TrackArtists', to='listening.artist'),
        ),
        migrations.CreateModel(
            name='TrackCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ManyToManyField(related_name='covers', through='listening.TrackCover', to='listening.artist'),
        ),
        migrations.CreateModel(
            name='TrackFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='track',
            name='feat',
            field=models.ManyToManyField(related_name='feats', through='listening.TrackFeat', to='listening.artist'),
        ),
        migrations.CreateModel(
            name='TrackRemix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='track',
            name='remix',
            field=models.ManyToManyField(related_name='remixes', through='listening.TrackRemix', to='listening.artist'),
        ),
    ]
