# Generated by Django 5.0.6 on 2024-06-20 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=500)),
                ('monitoring', models.BooleanField(default=False)),
                ('check_date', models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0))),
                ('releasing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('display_name', models.CharField(blank=True, max_length=300, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('display_title', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=500)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('is_clean', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(related_name='tracks', to='listening.artist')),
                ('feat', models.ManyToManyField(related_name='feats', to='listening.artist')),
                ('releases', models.ManyToManyField(related_name='tracks', to='listening.release')),
                ('remix', models.ManyToManyField(related_name='remixes', to='listening.artist')),
            ],
        ),
    ]
