# Generated by Django 4.0.4 on 2022-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='alias',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='track',
            name='alias',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
