# Generated by Django 4.0.4 on 2022-09-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_artist_alias_track_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='releasing',
            field=models.BooleanField(default=True),
        ),
    ]
