# Generated by Django 4.2.7 on 2024-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0003_artist_releasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='in_playlist',
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='listening.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='feat',
            field=models.ManyToManyField(related_name='feats', to='listening.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='remix',
            field=models.ManyToManyField(related_name='remixes', to='listening.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='alias',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='alias',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='track',
            name='releases',
            field=models.ManyToManyField(related_name='tracks', to='listening.release'),
        ),
    ]
