# Generated by Django 4.2.7 on 2024-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0004_release_remove_track_artist_remove_track_in_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='display_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='display_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
