# Generated by Django 3.0.6 on 2020-05-21 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=800)),
                ('year', models.IntegerField(blank=True, max_length=5)),
                ('type', models.CharField(choices=[('Anime', 'Anime'), ('Movie', 'Movie'), ('Serial', 'Serial')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('side_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watching.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('season_number', models.IntegerField(default=1)),
                ('episode_number', models.IntegerField(default=1)),
                ('current_episode', models.IntegerField(default=0)),
                ('watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='watching.Video')),
            ],
        ),
    ]
