# Generated by Django 5.0.6 on 2024-06-20 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=1000)),
                ('links_arr', models.CharField(blank=True, max_length=3000)),
                ('type', models.CharField(choices=[('Anime', 'Anime'), ('Movie', 'Movie'), ('Serial', 'Serial')], max_length=50)),
                ('single', models.BooleanField()),
                ('airing_status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Unknown', 'Unknown')], max_length=50)),
                ('check_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, choices=[('Dropped', 'Dropped'), ('Planned', 'Planned'), ('Ignored', 'Ignored'), ('Premiere', 'Premiere'), ('Watching', 'Watching'), ('Finished', 'Finished')], max_length=50)),
                ('watched_date', models.DateField(blank=True, default=None, null=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video/image/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='watching.group')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('alias', models.CharField(blank=True, max_length=1000)),
                ('links_arr', models.CharField(blank=True, max_length=3000)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Dropped', 'Dropped'), ('Planned', 'Planned'), ('Ignored', 'Ignored'), ('Premiere', 'Premiere'), ('Watching', 'Watching'), ('Finished', 'Finished')], max_length=50)),
                ('order', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('current_episode', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('watched_date', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='watching.group')),
            ],
        ),
    ]
