# Generated by Django 3.0.6 on 2020-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
