# Generated by Django 3.0.6 on 2020-05-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0002_auto_20200521_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='watched_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='side_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watching.Video'),
        ),
    ]
