# Generated by Django 3.0.6 on 2020-05-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0003_auto_20200521_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='side_story',
        ),
        migrations.AddField(
            model_name='video',
            name='parent_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='side_story', to='watching.Video'),
        ),
    ]
