# Generated by Django 4.0.4 on 2022-08-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0004_alter_group_rating_alter_group_year_alter_video_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='airing_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Completed', max_length=50),
        ),
    ]
