# Generated by Django 3.0.6 on 2020-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0004_auto_20200521_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Airing', 'Airing'), ('On Hold', 'On Hold'), ('Not Watching', 'Not Watching')], default='Finished', max_length=50),
        ),
    ]
