# Generated by Django 4.0.4 on 2022-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0005_alter_group_airing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='airing_status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Completed', max_length=50),
        ),
    ]
