# Generated by Django 3.0.6 on 2020-07-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0005_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
