# Generated by Django 3.1.7 on 2021-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0008_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='video/image/'),
        ),
    ]
