# Generated by Django 4.0.4 on 2022-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0011_group_links_video_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='links',
            new_name='links_arr',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='links',
            new_name='links_arr',
        ),
    ]
