# Generated by Django 3.1.7 on 2021-07-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0011_auto_20210705_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='root_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='watching.videogroup'),
        ),
    ]
