# Generated by Django 3.1.7 on 2021-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0012_video_root_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogroup',
            name='type',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movie', 'Movie'), ('Serial', 'Serial')], default='Anime', max_length=50),
        ),
    ]
