# Generated by Django 3.1.7 on 2021-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0013_videogroup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
