# Generated by Django 3.1.7 on 2021-07-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0014_video_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
