# Generated by Django 3.1.7 on 2021-07-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0015_auto_20210705_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='parent_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='root_group',
        ),
    ]
