# Generated by Django 3.1.7 on 2021-07-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0016_auto_20210705_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoGroup',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_group',
            new_name='group',
        ),
    ]
