# Generated by Django 3.1.7 on 2022-04-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0017_auto_20210705_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='watching.group'),
        ),
    ]
