# Generated by Django 3.1.7 on 2022-04-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0018_auto_20220422_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='video',
            new_name='group',
        ),
    ]
