# Generated by Django 3.1.7 on 2022-04-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0019_auto_20220422_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Movie', 'Movie'), ('Serial', 'Serial')], max_length=50),
        ),
    ]
