# Generated by Django 3.1.7 on 2022-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0020_auto_20220426_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
