# Generated by Django 3.1.7 on 2022-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0022_auto_20220426_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='single',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(blank=True, choices=[('Dropped', 'Dropped'), ('Planned', 'Planned'), ('Ignored', 'Ignored'), ('Watching', 'Watching'), ('Finished', 'Finished')], max_length=50, null=True),
        ),
    ]
