# Generated by Django 3.1.7 on 2022-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0024_auto_20220427_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
