# Generated by Django 3.1.7 on 2022-04-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0026_auto_20220430_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watched_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
