# Generated by Django 3.1.7 on 2022-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watching', '0027_video_watched_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='airing_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=50),
            preserve_default=False,
        ),
    ]
