# Generated by Django 4.0.4 on 2022-07-30 13:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('number', models.IntegerField(default=1)),
                ('inspected', models.BooleanField(default=False)),
                ('parsed', models.BooleanField(default=False)),
                ('download_status', models.CharField(choices=[('DOWNLOADED', 'DOWNLOADED'), ('UNABLE', 'UNABLE'), ('MISSING', 'MISSING')], max_length=50)),
                ('type', models.CharField(choices=[('Single', 'Single'), ('Playlist', 'Playlist')], max_length=50)),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime(2001, 1, 1, 0, 0), null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContentWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('watcher_id', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('Youtube', 'Youtube'), ('Bandcamp', 'Bandcamp')], max_length=50)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Running', 'Running'), ('Finished', 'Finished'), ('Warning', 'Warning'), ('Error', 'Error'), ('Dead', 'Dead')], max_length=50)),
                ('check_date', models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0))),
                ('download_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('file_extension', models.CharField(choices=[('mp3', 'mp3'), ('mp4', 'mp4'), ('mkv', 'mkv')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_watcher', to='contenting.contentlist')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ADD', 'ADD'), ('SKIP', 'SKIP'), ('DUPLICATE', 'DUPLICATE')], max_length=50)),
                ('needs_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_part', to='contenting.contentitem')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_part', to='listening.track')),
            ],
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_item', to='contenting.contentlist'),
        ),
    ]
