# Generated by Django 4.0.4 on 2022-08-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
        ('contenting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='contenting.contentlist'),
        ),
        migrations.AlterField(
            model_name='contentitempart',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_parts', to='contenting.contentitem'),
        ),
        migrations.AlterField(
            model_name='contentitempart',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_parts', to='listening.track'),
        ),
    ]
