# Generated by Django 4.0.4 on 2022-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0002_alter_contentitem_content_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentwatcher',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Running', 'Running'), ('Finished', 'Finished'), ('Warning', 'Warning'), ('Error', 'Error'), ('Dead', 'Dead'), ('None', 'None')], max_length=50),
        ),
    ]
