# Generated by Django 4.2.7 on 2023-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0004_alter_contentitem_download_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentwatcher',
            old_name='download_count',
            new_name='items_count',
        ),
        migrations.AddField(
            model_name='contentwatcher',
            name='download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentwatcher',
            name='video_quality',
            field=models.IntegerField(blank=True, choices=[('720', 720), ('1080', 1080), ('Default', None)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contentwatcher',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Running', 'Running'), ('Finished', 'Finished'), ('Warning', 'Warning'), ('Error', 'Error'), ('Dead', 'Dead'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
