# Generated by Django 4.2.7 on 2024-05-18 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0005_rename_download_count_contentwatcher_items_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitempart',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contentitempart',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contentlist',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Fun', 'Fun'), ('Game', 'Game'), ('Tech', 'Tech'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='download_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('DOWNLOADING', 'DOWNLOADING'), ('DOWNLOADED', 'DOWNLOADED'), ('UNABLE', 'UNABLE'), ('MISSING', 'MISSING'), ('SKIP', 'SKIP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contentitempart',
            name='start_time',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
