# Generated by Django 4.2.7 on 2024-05-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0006_contentitempart_duration_contentitempart_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentitem',
            old_name='number',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='contentitempart',
            old_name='number',
            new_name='position',
        ),
    ]
