# Generated by Django 4.2.7 on 2024-05-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0007_rename_number_contentitem_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwatcher',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Fun', 'Fun'), ('Game', 'Game'), ('Tech', 'Tech'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
    ]
