# Generated by Django 4.2.7 on 2024-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0009_contentmusicitem_contenttrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlist',
            name='migration_position',
            field=models.IntegerField(default=0),
        ),
    ]
