# Generated by Django 4.2.7 on 2024-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0011_alter_contentmusicitem_content_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttrack',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
