# Generated by Django 4.2.7 on 2024-05-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0006_track_is_clean'),
        ('contenting', '0012_alter_contenttrack_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='download_status',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('DOWNLOADING', 'DOWNLOADING'), ('DOWNLOADED', 'DOWNLOADED'), ('UNABLE', 'UNABLE'), ('MISSING', 'MISSING'), ('SKIP', 'SKIP')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentmusicitem',
            name='download_status',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('DOWNLOADING', 'DOWNLOADING'), ('DOWNLOADED', 'DOWNLOADED'), ('UNABLE', 'UNABLE'), ('MISSING', 'MISSING'), ('SKIP', 'SKIP')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='contenttrack',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_tracks', to='listening.track'),
        ),
    ]
