# Generated by Django 5.0.6 on 2024-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenting', '0013_alter_contentitem_download_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentwatcher',
            name='items_count',
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='download_status',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PENDING', 'PENDING'), ('DOWNLOADING', 'DOWNLOADING'), ('DOWNLOADED', 'DOWNLOADED'), ('UNABLE', 'UNABLE'), ('MISSING', 'MISSING'), ('SKIP', 'SKIP')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentmusicitem',
            name='download_status',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PENDING', 'PENDING'), ('DOWNLOADING', 'DOWNLOADING'), ('DOWNLOADED', 'DOWNLOADED'), ('UNABLE', 'UNABLE'), ('MISSING', 'MISSING'), ('SKIP', 'SKIP')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentwatcher',
            name='file_extension',
            field=models.CharField(choices=[('mkv', 'mkv'), ('mp4', 'mp4'), ('mp3', 'mp3'), ('m4a', 'm4a')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contentwatcher',
            name='video_quality',
            field=models.IntegerField(blank=True, choices=[(720, '720'), (1080, '1080'), ('Default', None)], default=None, null=True),
        ),
    ]
